import { Task } from "./types";

export const mockTasks: Task[] = [
  {
    id: "t1",
    title: "Design the new onboarding flow",
    dueDate: "Today",
    priority: "high",
    tags: ["design", "ux"],
    notes: "Focus on the first-time user experience. Use the new component library for consistency.",
    subtasks: [
      { id: "t1s1", title: "Sketch wireframes", done: true },
      { id: "t1s2", title: "Create Figma prototype", done: false },
    ],
    completed: false,
    list: "today",
  },
  {
    id: "t2",
    title: "Review architecture proposal",
    dueDate: "Today",
    priority: "medium",
    tags: ["dev"],
    notes: "",
    subtasks: [],
    completed: false,
    list: "today",
  },
  {
    id: "t3",
    title: "Write weekly reflection",
    dueDate: "Today",
    priority: "low",
    tags: ["growth"],
    notes: "Three wins, one lesson learned, one goal for next week.",
    subtasks: [],
    completed: false,
    list: "today",
  },
  {
    id: "u1",
    title: "Prepare investor demo",
    dueDate: "May 28",
    priority: "high",
    tags: ["work", "presentation"],
    notes: "Include growth metrics and user retention data. Rehearse with the team first.",
    subtasks: [
      { id: "u1s1", title: "Compile metrics deck", done: true },
      { id: "u1s2", title: "Record walkthrough video", done: true },
      { id: "u1s3", title: "Dry run with mentors", done: false },
    ],
    completed: false,
    list: "upcoming",
  },
  {
    id: "u2",
    title: "Research meditation techniques",
    dueDate: "May 30",
    priority: "low",
    tags: ["wellness"],
    notes: "",
    subtasks: [],
    completed: false,
    list: "upcoming",
  },
  {
    id: "i1",
    title: 'Read "Deep Work" chapter 5',
    dueDate: "",
    priority: "low",
    tags: ["reading"],
    notes: "",
    subtasks: [],
    completed: false,
    list: "inbox",
  },
  {
    id: "i2",
    title: "Review design system updates",
    dueDate: "",
    priority: "medium",
    tags: ["design", "dev"],
    notes: "",
    subtasks: [],
    completed: false,
    list: "inbox",
  },
  {
    id: "p1",
    title: "Plan weekend hiking trip",
    dueDate: "May 25",
    priority: "low",
    tags: ["outdoor"],
    notes: "Check weather, prepare gear, pack snacks. Invite the group.",
    subtasks: [
      { id: "p1s1", title: "Check trail conditions", done: true },
      { id: "p1s2", title: "Pack backpack", done: false },
      { id: "p1s3", title: "Buy trail snacks", done: false },
    ],
    completed: false,
    list: "personal",
  },
  {
    id: "p2",
    title: "Call mom",
    dueDate: "Today",
    priority: "medium",
    tags: ["family"],
    notes: "",
    subtasks: [],
    completed: false,
    list: "personal",
  },
  {
    id: "s1",
    title: "Complete advanced TypeScript module",
    dueDate: "Jun 2",
    priority: "high",
    tags: ["dev", "learning"],
    notes: "",
    subtasks: [],
    completed: false,
    list: "study",
  },
  {
    id: "s2",
    title: "Review machine learning notes",
    dueDate: "May 27",
    priority: "medium",
    tags: ["study", "ai"],
    notes: "Focus on the neural network section. Re-do the exercises.",
    subtasks: [
      { id: "s2s1", title: "Read chapter 7", done: false },
      { id: "s2s2", title: "Complete exercise set", done: false },
    ],
    completed: false,
    list: "study",
  },
  {
    id: "w1",
    title: "Finalize Q2 strategy document",
    dueDate: "May 26",
    priority: "high",
    tags: ["work", "strategy"],
    notes: "Align with team leads before the board meeting. Include revenue projections.",
    subtasks: [],
    completed: false,
    list: "work",
  },
  {
    id: "e1",
    title: "Morning yoga — 30 min",
    dueDate: "Today",
    priority: "low",
    tags: ["wellness", "routine"],
    notes: "",
    subtasks: [],
    completed: false,
    list: "exercise",
  },
  {
    id: "e2",
    title: "5k training run",
    dueDate: "May 25",
    priority: "medium",
    tags: ["fitness"],
    notes: "",
    subtasks: [],
    completed: false,
    list: "exercise",
  },
  {
    id: "sh1",
    title: "Buy new running shoes",
    dueDate: "",
    priority: "none",
    tags: ["shopping"],
    notes: "",
    subtasks: [],
    completed: false,
    list: "shopping",
  },
  {
    id: "c1",
    title: "Set up CI/CD pipeline",
    dueDate: "Done",
    priority: "medium",
    tags: ["dev", "ops"],
    notes: "",
    subtasks: [],
    completed: true,
    list: "inbox",
  },
  {
    id: "c2",
    title: "Order desk plants",
    dueDate: "Done",
    priority: "low",
    tags: ["personal"],
    notes: "",
    subtasks: [],
    completed: true,
    list: "personal",
  },
];
